---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: quarterly
    groups:
      gomod-deps:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly
    groups:
      actions-deps:
        patterns:
          - "*"
